In [94]:
import numpy as np

## Data Types and Attributes
Numpy's main datatype is ndarray(n-dimensional array) 

In [95]:
a1=np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [96]:
type(a1)

numpy.ndarray

## 2D array

In [97]:
a2=np.array([[1,2,3,4],
             [5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 3D array

In [98]:
a3=np.array([[[1,2,3,4],
      [5,6,7,8],
     [12,23,34,56]],
     
     [[8,7,6,5],
      [2.3,4.5,0,9],
      [4,3,2,1]]])
a3

array([[[ 1. ,  2. ,  3. ,  4. ],
        [ 5. ,  6. ,  7. ,  8. ],
        [12. , 23. , 34. , 56. ]],

       [[ 8. ,  7. ,  6. ,  5. ],
        [ 2.3,  4.5,  0. ,  9. ],
        [ 4. ,  3. ,  2. ,  1. ]]])

In [99]:
a1.shape,a2.shape,a3.shape #number of row,columns of array

((6,), (2, 4), (2, 3, 4))

In [100]:
a1.ndim,a2.ndim,a3.ndim #dimension of array

(1, 2, 3)

In [101]:
a1.dtype,a2.dtype,a3.dtype #data type of array

(dtype('int64'), dtype('int64'), dtype('float64'))

In [102]:
a1.size,a2.size,a3.size #size of array

(6, 8, 24)

In [103]:
type(a1),type(a2),type(a3)#type of array

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [104]:
import pandas as pd #creating dataframe out of array
df=pd.DataFrame(a2)
df

0  1  2  3
0  1  2  3  4
1  5  6  7  8

## Creating Numpy array

In [105]:
sample=np.array([1,2,3,4])
sample

array([1, 2, 3, 4])

In [106]:
ones=np.ones((2,3),dtype=int)
#default float type so dtype specified
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [107]:
zeros=np.zeros((2,3),dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [108]:
range_array=np.arange(1,10,2)
range_array

array([1, 3, 5, 7, 9])

In [109]:
random_array=np.random.randint(0,10,(2,3))
random_array

array([[8, 1, 3],
       [3, 3, 7]])

In [110]:
random_array1=np.random.random((2,3))
random_array1

array([[0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561]])

In [111]:
random_array2=np.random.rand(2,3)
random_array2

array([[0.77423369, 0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 , 0.61209572]])

In [112]:
np.random.seed(seed=7) #numbers do not change when rerun ,seed can be any number
random_array3=np.random.rand(2,3)
random_array3

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587]])

In [113]:
np.unique(random_array) #gives unique numbers in a array

array([1, 3, 7, 8])

## Viewing arrays and matrics

In [114]:
a1,a2,a3 #arrays from above

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[[ 1. ,  2. ,  3. ,  4. ],
         [ 5. ,  6. ,  7. ,  8. ],
         [12. , 23. , 34. , 56. ]],
 
        [[ 8. ,  7. ,  6. ,  5. ],
         [ 2.3,  4.5,  0. ,  9. ],
         [ 4. ,  3. ,  2. ,  1. ]]]))

In [115]:
a1[0] #return element at index 0

1

In [116]:
a2[0] #return row at index 0

array([1, 2, 3, 4])

In [117]:
a3

array([[[ 1. ,  2. ,  3. ,  4. ],
        [ 5. ,  6. ,  7. ,  8. ],
        [12. , 23. , 34. , 56. ]],

       [[ 8. ,  7. ,  6. ,  5. ],
        [ 2.3,  4.5,  0. ,  9. ],
        [ 4. ,  3. ,  2. ,  1. ]]])

In [118]:
a2[:2, :2]

array([[1, 2],
       [5, 6]])

In [119]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[8, 9, 8, 7, 6],
         [4, 0, 7, 0, 7],
         [6, 3, 5, 8, 8],
         [7, 5, 0, 0, 2]],

        [[8, 9, 6, 4, 9],
         [7, 3, 3, 8, 3],
         [0, 1, 0, 0, 6],
         [7, 7, 9, 3, 0]],

        [[7, 7, 7, 0, 5],
         [4, 3, 1, 3, 1],
         [3, 4, 3, 1, 9],
         [5, 9, 1, 2, 3]]],


       [[[2, 2, 5, 7, 3],
         [0, 9, 9, 3, 4],
         [5, 3, 0, 4, 8],
         [6, 7, 2, 7, 3]],

        [[8, 6, 6, 5, 6],
         [5, 7, 1, 5, 4],
         [4, 9, 9, 0, 6],
         [2, 6, 8, 2, 4]],

        [[1, 6, 1, 5, 1],
         [6, 9, 8, 6, 5],
         [9, 7, 5, 4, 9],
         [6, 8, 1, 5, 5]]]])

In [120]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [121]:
#get first 4 numbers of inner most array
a4[:, :, :, :4]

array([[[[8, 9, 8, 7],
         [4, 0, 7, 0],
         [6, 3, 5, 8],
         [7, 5, 0, 0]],

        [[8, 9, 6, 4],
         [7, 3, 3, 8],
         [0, 1, 0, 0],
         [7, 7, 9, 3]],

        [[7, 7, 7, 0],
         [4, 3, 1, 3],
         [3, 4, 3, 1],
         [5, 9, 1, 2]]],


       [[[2, 2, 5, 7],
         [0, 9, 9, 3],
         [5, 3, 0, 4],
         [6, 7, 2, 7]],

        [[8, 6, 6, 5],
         [5, 7, 1, 5],
         [4, 9, 9, 0],
         [2, 6, 8, 2]],

        [[1, 6, 1, 5],
         [6, 9, 8, 6],
         [9, 7, 5, 4],
         [6, 8, 1, 5]]]])

In [122]:
#get first 1 numbers of inner most array
a4[:, :, :, :1]

array([[[[8],
         [4],
         [6],
         [7]],

        [[8],
         [7],
         [0],
         [7]],

        [[7],
         [4],
         [3],
         [5]]],


       [[[2],
         [0],
         [5],
         [6]],

        [[8],
         [5],
         [4],
         [2]],

        [[1],
         [6],
         [9],
         [6]]]])

## Manipulating and comparing arraya

### Arithematic

In [123]:
a1=a1.reshape(2,3) #shapes should be same so reshape is used

In [124]:
a1,ones

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 1, 1],
        [1, 1, 1]]))

In [125]:
a1+ones

array([[2, 3, 4],
       [5, 6, 7]])

In [126]:
np.add(a1,ones)

array([[2, 3, 4],
       [5, 6, 7]])

In [127]:
a1-ones

array([[0, 1, 2],
       [3, 4, 5]])

In [128]:
np.subtract(a1,ones)

array([[0, 1, 2],
       [3, 4, 5]])

In [129]:
ones*2

array([[2, 2, 2],
       [2, 2, 2]])

In [130]:
np.multiply(ones,2)

array([[2, 2, 2],
       [2, 2, 2]])

In [131]:
a1*ones

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
a1/ones

array([[1., 2., 3.],
       [4., 5., 6.]])

In [133]:
a1[:3]*a2[:,:3]

array([[ 1,  4,  9],
       [20, 30, 42]])

In [134]:
a1%2

array([[1, 0, 1],
       [0, 1, 0]])

In [135]:
a1//2 #return rounded value

array([[0, 1, 1],
       [2, 2, 3]])

In [136]:
np.exp(a1).round()

array([[  3.,   7.,  20.],
       [ 55., 148., 403.]])

In [137]:
np.log(a1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

### Aggregation
aggregation =preforming some operation on number(cluster)of things

In [138]:
list1=[1,2,3]
sum(list1)

6

In [139]:
sum(a1)

array([5, 7, 9])

Use python method('sum()') on pythondatatypes and Numpy method ('np.sum()')
on numpy datatypes.

In [140]:
#creating massive numpy array
huge=np.random.random(100000)
huge[:100]

array([0.9435772 , 0.73779928, 0.041573  , 0.75778036, 0.513401  ,
       0.17842575, 0.39200156, 0.93959276, 0.21291858, 0.81329627,
       0.40364858, 0.58672092, 0.18599889, 0.81232251, 0.58084741,
       0.44693254, 0.79808141, 0.54427185, 0.41841659, 0.01915666,
       0.68377373, 0.48809792, 0.22057967, 0.55054305, 0.52259111,
       0.48755248, 0.26303148, 0.52728579, 0.98446573, 0.62342345,
       0.62955693, 0.9099729 , 0.96251949, 0.5850998 , 0.16489774,
       0.39159332, 0.94455493, 0.34339118, 0.70507037, 0.4628868 ,
       0.38679069, 0.52843256, 0.82168992, 0.63847702, 0.86288872,
       0.63662654, 0.99929706, 0.51778008, 0.32761664, 0.09877324,
       0.5667664 , 0.21520794, 0.01179079, 0.29921532, 0.03897743,
       0.97621382, 0.55145308, 0.07171621, 0.34006782, 0.24290239,
       0.10735082, 0.77033058, 0.35060155, 0.18764274, 0.91265269,
       0.86114826, 0.39889823, 0.54633644, 0.45037544, 0.69359919,
       0.21384609, 0.3237989 , 0.73989292, 0.18257051, 0.69602

In [141]:
%timeit sum(huge) #python sum( ) time
%timeit np.sum(huge) #numpy np.sum() time

10.9 ms ± 232 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
55.7 µs ± 5.12 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [142]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [143]:
np.mean(a2)

4.5

In [144]:
np.max(a2)

8

In [145]:
np.min(a2)

1

In [146]:
np.std(a2) #standard deviation

2.29128784747792

In [147]:
np.var(a2) #variance

5.25

### reshaping and transpose

In [148]:
a2,a3

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[[ 1. ,  2. ,  3. ,  4. ],
         [ 5. ,  6. ,  7. ,  8. ],
         [12. , 23. , 34. , 56. ]],
 
        [[ 8. ,  7. ,  6. ,  5. ],
         [ 2.3,  4.5,  0. ,  9. ],
         [ 4. ,  3. ,  2. ,  1. ]]]))

In [149]:
a2.T.shape

(4, 2)

In [150]:
a2.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Dot product

In [151]:
np.random.seed(7)
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))
mat1,mat2

(array([[4, 9, 6],
        [3, 3, 7],
        [7, 9, 7],
        [8, 9, 8],
        [7, 6, 4]]),
 array([[0, 7, 0],
        [7, 6, 3],
        [5, 8, 8],
        [7, 5, 0],
        [0, 2, 8]]))

In [152]:
#element wise multiplication (hadamard product)
mat1*mat2

array([[ 0, 63,  0],
       [21, 18, 21],
       [35, 72, 56],
       [56, 45,  0],
       [ 0, 12, 32]])

In [153]:
mat3=np.dot(mat1,mat2.T)

In [154]:
mat3

array([[ 63, 100, 140,  73,  66],
       [ 21,  60,  95,  36,  62],
       [ 63, 124, 163,  94,  74],
       [ 63, 134, 176, 101,  82],
       [ 42,  97, 115,  79,  44]])

In [155]:
np.random.seed(0)
sales=np.random.randint(20,size=(5,3))
sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [156]:
weekly_sales=pd.DataFrame(sales,index=["mon",'tue','wed','thr','fri'],columns=['almond','peanut','cashew'])
weekly_sales

almond  peanut  cashew
mon      12      15       0
tue       3       3       7
wed       9      19      18
thr       4       6      12
fri       1       6       7

In [157]:
prices=np.array([10,8,12])
prices

array([10,  8, 12])

In [158]:
nut_price=pd.DataFrame(prices.reshape(1,3),index=['Prices'],columns=['almond','peanut','cashew'])
nut_price

almond  peanut  cashew
Prices      10       8      12

In [159]:
total=prices.dot(sales.T)
total

array([240, 138, 458, 232, 142])

In [160]:
daily_sales=nut_price.dot(weekly_sales.T)
daily_sales

mon  tue  wed  thr  fri
Prices  240  138  458  232  142

In [161]:
daily_sales.shape

(1, 5)

In [162]:
weekly_sales["Total"]=daily_sales.T
weekly_sales

almond  peanut  cashew  Total
mon      12      15       0    240
tue       3       3       7    138
wed       9      19      18    458
thr       4       6      12    232
fri       1       6       7    142

### comparting operators

In [163]:
a1,a2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [164]:
a1>a2[ :,:3]

array([[False, False, False],
       [False, False, False]])

In [165]:
a1<a2[:,:3]

array([[False, False, False],
       [ True,  True,  True]])

In [166]:
a1==a1

array([[ True,  True,  True],
       [ True,  True,  True]])

### sorting array

In [167]:
random=np.random.randint(10,size=(3,5))
random

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [168]:
np.sort(random)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [169]:
np.argsort(random)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [170]:
np.argmax(random,axis=0)

array([1, 1, 1, 0, 0])

In [171]:
np.argmax(random,axis=1)

array([4, 1, 1])

<img src="Python-logo-notext.svg.png"/>

In [172]:
#turn image into an numpy array
from matplotlib.image import imread

In [173]:
python=imread("Python-logo-notext.svg.png")
type(python)

numpy.ndarray

In [174]:
python.size,python.shape,python.ndim

(15310848, (2048, 1869, 4), 3)

In [175]:
python

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0.